### ISSUE TITLE
general store stock report

### ISSUE THREAD

**Issue by piumini** [buddhika75/hmis#247]
general store stock report is printed with duplicate item name, zero qty ...

**Comment by buddhika75** [comment]
In batch report, there can be duplicate names of items as they are shown in batches. I checked, but there was no items with zero quantities.

New Report By Item.There will be no duplicates of names or with zero quantities as it lists items rather than batches.

Report cab be accesses through Menu > Stores > Reports > Stock Reports > Department Stock By Item. That lists in a paginated table.

You can take printout of all the pages at once.

![issue-248](https://cloud.githubusercontent.com/assets/1226946/7827593/e237fc9e-0446-11e5-9400-8adb49f0071f.png)
![issue-248-a](https://cloud.githubusercontent.com/assets/1226946/7827594/e23a7dd4-0446-11e5-95d6-126f6e9a5ef6.png)

**Comment by buddhika75** [comment]
Pull the latest commit d73348308aefe452d9deb7e2cc28b666da6088fc for the new report.
Close if you are satisfied.

**Comment by piumini** [comment]
ok
