### ISSUE TITLE
pharmacy

### ISSUE THREAD

**Issue by piumini** [buddhika75/hmis#255]
![add to](https://cloud.githubusercontent.com/assets/7201585/7806898/c172e918-03a3-11e5-9615-b1ef384cdff6.png)

**Comment by lahirumadushanka** [comment]
please put issues in detail.......which pharmacy is this??

**Comment by lahirumadushanka** [comment]
RHMPSALE/72368 w kosal nadeeshani and k g lakshani nikeshala settle both bills in last second, so two bills were created for one pharmacy bill.after 5-6 days w kosal nadeeshani cancelled her bill got it on her summery and k g lakshani nikeshala was left her bill didn't get summery at that time. my suggestion for this if this bill really needed to add to stock, find that sale bill and retire it.don't cancel it because it may reduce the summery. if this is unclear please contact us.

**Comment by lahirumadushanka** [comment]
RHMPSALE/6144 bill is settle without billitems. check whether that time was sever down.

**Comment by lahirumadushanka** [comment]
sorry for that RHMPSALE/72368 doesnt have an issue this bill was accepted by two cashiers at the same time. k g lakshani nikeshala and w kosal nadeeshani.w kosal nadeeshani was cancelled and k g lakshani nikeshala bill wasnt cancelled that's why that that bill can't add to stock. so please find that bill and cancel it by same user.

**Comment by piumini** [comment]
ok
